name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - uses: mansona/npm-lockfile-version@v1
      - run: npm i -g npm@7
      - run: npm ci
      - run: npm test
